DB_JSON = "D:\\Python\\RAG_v1\\Database\\dataTest.json"
DB_AFTER_CHUNK = "D:\\Python\\RAG_v1\\Database\\dataTest_after_chunk.json"
OUTPUT_DIR = "D:\\Python\\RAG_v1\\Database\\output"
INDEX_PATH = "D:\\Python\\RAG_v1\\Database\\output\\faiss_index.idx"
META_PATH = "D:\\Python\\RAG_v1\\Database\\output\\faiss_metadata.pkl"